"""
This type stub file was generated by pyright.
"""

def hypervolume(front, **kargs) -> intp:
    """Returns the index of the individual with the least the hypervolume
    contribution. The provided *front* should be a set of non-dominated
    individuals having each a :attr:`fitness` attribute.

    The hypervolume is computed using the `moocore` package.
    See :func:`moocore.hypervolume` for details.
    """
    ...

__all__ = ["hypervolume"]
